### ISSUE TITLE
Checkpoints

### ISSUE THREAD

**Issue by morrisons90** [GerhartPapaGee/Overthrow-Martial-Law#1]
Checkpoints having gates
Checkpoints searching area reduced
Checkpoints no return zone reduced
Checkpoint warning zone added

**Comment by morrisons90** [comment]
To Do: Add support for different checkpoint templates

**Comment by morrisons90** [comment]
Rewrote the search system to detect Ammoboxes and search them and static weapons in the ace cargo.
Also, the system also does not dump items into vehicle inv.

Be aware when testing, Arsenal opened via debug seems to disable chat so you won't be able to see checkpoint messages.

**Comment by morrisons90** [comment]
Fixed the vehicle not being searched. Should work now.

**Comment by GerhartPapaGee** [comment]
Seems like everything is working as far as I can tell
