### ISSUE TITLE
Change from using "custom icons" to using "custom markers"

### ISSUE THREAD

**Issue by GerhartPapaGee** [GerhartPapaGee/Overthrow-Martial-Law#14]
Change from using "custom icons" for businesses, shops, factory to using markers instead, hopefully custom markers.  Hopefully to help stop the "map crashes" that many suffer from.  If possible to change from using the icons to markers then add a marker for the car dealer also.

**Comment by morrisons90** [comment]
Should not take too long, I hate the map crashes. Any idea of how you would like to show different shops?

**Comment by GerhartPapaGee** [comment]
Would it be possible to make custom markers from the custom icons in the mod?

**Comment by GerhartPapaGee** [comment]
Deadorbit has a temp solution until this can be fixed.  I posted it in the "tips -n-tricks" section on discord
