### ISSUE TITLE
Bug?  Infinite inventory on specific vehicles? 

### ISSUE THREAD

**Issue by GerhartPapaGee** [GerhartPapaGee/Overthrow-Martial-Law#15]
Can this be fixed so that isn't possible?

**Comment by morrisons90** [comment]
This is mentioned in the ot wiki as a feature. Should just be a case of adding an inventory check like the rest of the vehicles

**Comment by GerhartPapaGee** [comment]
No shit?!  What a strange feature to have

**Comment by deadorbit** [comment]
The thing is it first checks if the vehicle is a certain type to see if it should whether or not the item should fit, but its using old config names from the beta so no vehicle ends up fitting in those classes.

**Comment by GerhartPapaGee** [comment]
Need to discuss if this feature should be removed or not.
