### ISSUE TITLE
Add illegal uniforms specifically Military uniforms.  

### ISSUE THREAD

**Issue by morrisons90** [GerhartPapaGee/Overthrow-Martial-Law#18]
Wearing these uniforms should be illegal for the player to have or wear

**Comment by morrisons90** [comment]
Are you sure this isn't already illegal for some uniforms?

**Comment by GerhartPapaGee** [comment]
I haven't seen anything indicating uniforms to be illegal.  The only things wearable that are illegal are NVG, armored vests, armored helmets except hardhats, skater helmets and motorcycle helmets.
