### ISSUE TITLE
Backpack shop sells MG's and ATGM's for less than $100

### ISSUE THREAD

**Issue by morrisons90** [GerhartPapaGee/Overthrow-Martial-Law#4]
Way too cheap. Makes the game too easy.

I think @deadorbit might have a solution for this already?

**Comment by deadorbit** [comment]
Well Its kinda a solution, I like it but you (and Gerheart may think otherwise) I just removed it from trying to auto-detect and classify backpacks and instead manually set what backpacks are for sale.

**Comment by morrisons90** [comment]
What about an even lazier solution? If it is auto-detecting backpacks ( which I did not know ) then add a blacklist?

**Comment by deadorbit** [comment]
I do think I have found a better solution, while personally I like whitelisting things, if you (and Gerheart) enjoy the idea of having things auto generated, I think there is already a command to keep it from taking backpacks with items into them for sale. https://community.bistudio.com/wiki/BIS_fnc_basicBackpack returns a backpack that is tempt.

**Comment by morrisons90** [comment]
@deadorbit brilliant, how do you find all these amazing functions?!?

**Comment by deadorbit** [comment]
A lot of aggressive googling
