### ISSUE TITLE
Vehicle spawns need looked at to prevent spawnosions ( spawn explosions ).

### ISSUE THREAD

**Issue by GerhartPapaGee** [GerhartPapaGee/Overthrow-Martial-Law#8]

**Comment by deadorbit** [comment]
Something I've "mostly" managed to fix on mine already so shouldn't be any problem to fix for ML

**Comment by deadorbit** [comment]
I'm a bit confused, is MaxP gonna fix this or am i?

**Comment by morrisons90** [comment]
Have you seen the suggestion that MaxP has put in discord? It looks like the root of this problem is vehicles spawning on top of eachother. This could be duplicated spawning or bad safe position finding. Something good for all our versions

**Comment by GerhartPapaGee** [comment]
The transport heli's suffer from spawning on the  same helipad at times, I've watched it happen in Zeus.  The attack chopper just spawns and boom most of the time, same deal watched it in Zeus
